artifact_uri: file:///C:/Users/R4G/Desktop/ML%26DSProjects/Telco_Customer_Churn_Model/mlruns/273200537397394520/abf9a1b58b5b42dd8c308a1ff6d567d6/artifacts
end_time: 1776450524136
entry_point_name: ''
experiment_id: '273200537397394520'
lifecycle_stage: active
run_id: abf9a1b58b5b42dd8c308a1ff6d567d6
run_name: casual-skink-575
source_name: ''
source_type: 4
source_version: ''
start_time: 1776450524056
status: 4
tags: []
user_id: R4G
